// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQG58nyruo1dhLWcoDz2vpM3wQHjRMu5c',
    appId: '1:826222626361:android:f52a95ef0b3c005fff6fe8',
    messagingSenderId: '826222626361',
    projectId: 'health-sudan-app',
    storageBucket: 'health-sudan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCELQKtq_5i0ngRwtn7AaV3_r0ej-i3hmM',
    appId: '1:826222626361:ios:5ca43ead686478a0ff6fe8',
    messagingSenderId: '826222626361',
    projectId: 'health-sudan-app',
    storageBucket: 'health-sudan-app.firebasestorage.app',
    iosBundleId: 'com.example.citizensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDezXDYAGDOqiSmoapVuwU3j47tF3cdczg',
    appId: '1:826222626361:web:64041c87f92796e1ff6fe8',
    messagingSenderId: '826222626361',
    projectId: 'health-sudan-app',
    authDomain: 'health-sudan-app.firebaseapp.com',
    storageBucket: 'health-sudan-app.firebasestorage.app',
    measurementId: 'G-FLWG32G4QM',
  );
}
